{% set version = environ.get('GIT_DESCRIBE_TAG', '5.5.1').lstrip('v') %}
{% set build_number = environ.get('GIT_DESCRIBE_NUMBER', '0') %}

package:
  name: sqanti3
  version: {{ version }}

source:
  path: ..

build:
  number: {{ build_number }}
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - sqanti3 = sqanti3:main
    - sqanti3-qc = sqanti3_qc:main
    - sqanti3-filter = sqanti3_filter:main
    - sqanti3-rescue = sqanti3_rescue:main
    - sqanti3-reads = sqanti3_reads:main

requirements:
  host:
    - python >=3.11
    - pip
    - setuptools >=64
    - setuptools_scm >=8
  run:
    - python >=3.11
    # Core Python dependencies
    - numpy >=1.26.4
    - pandas >=2.2.3
    - scipy <=1.11.4
    - scikit-learn >=1.5.2
    - cython >=3.0.11
    - biopython <=1.81
    - pybedtools >=0.10.0
    - pysam >=0.22.1
    - bcbio-gff >=0.7.1
    - seaborn >=0.13.2
    - psutil >=6.1.0
    - jinja2 >=3.1.4
    - argcomplete >=3.4.0
    # Additional Python packages
    - gffutils >=0.13
    - gtfparse >=2.5.0
    - parasail >=1.3.4
    - edlib >=1.3.9.post1
    - intervaltree >=3.1.0
    - polars >=0.20.31
    - pyarrow >=14.0.2
    - pyfaidx >=0.8.1.3
    # Bioinformatics tools
    - bedtools >=2.31.1
    - gffread >=0.12.7
    - gtftools >=0.9.0
    - gmap >=2024.11.20
    - kallisto >=0.51.1
    - minimap2 >=2.28
    - samtools >=1.21
    - star >=2.7.11b
    - seqtk >=1.4
    - desalt >=1.5.6
    # R and R packages
    - r-base >=4.3.0
    - r-biocmanager >=1.30.25
    - r-caret >=6.0_94
    - r-dplyr >=1.1.4
    - r-dt >=0.33
    - r-devtools >=2.4.5
    - r-e1071 >=1.7_16
    - r-forcats >=1.0.0
    - r-ggplot2 >=3.4.0
    - r-ggplotify >=0.1.2
    - r-gridbase >=0.4_7
    - r-gridextra >=2.3
    - r-htmltools >=0.5.8.1
    - r-jsonlite >=1.8.9
    - r-optparse >=1.7.5
    - r-plotly >=4.10.4
    - r-plyr >=1.8.9
    - r-purrr >=1.0.2
    - r-randomforest >=4.7
    - r-rmarkdown >=2.29
    - r-reshape >=0.8.9
    - r-readr >=2.1.5
    - r-scales >=1.3.0
    - r-stringi >=1.8.4
    - r-stringr >=1.5.1
    - r-tibble >=3.2.1
    - r-tidyr >=1.3.1
    # Bioconductor packages
    - bioconductor-noiseq >=2.46.0
    - bioconductor-busparse >=1.16.0
    - bioconductor-gviz
    # Other dependencies
    - bx-python >=0.11.0
    - openssl >=3.5.0
    - pandoc >=3.5
    - perl >=5.32.1

test:
  imports:
    - src.config
  commands:
    - sqanti3 --version || sqanti3 -v || true
    - sqanti3-qc --help || sqanti3_qc.py --help || true
    - sqanti3-filter --help || sqanti3_filter.py --help || true
    - sqanti3-rescue --help || sqanti3_rescue.py --help || true
    - sqanti3-reads --help || sqanti3_reads.py --help || true
    - pytest --version

about:
  home: https://github.com/ConesaLab/SQANTI3
  license: BSD-3-Clause-Clear
  license_file: LICENSE
  summary: Tool for the Quality Control of Long-Read Defined Transcriptomes
  description: |
    SQANTI3 is the newest version of the SQANTI tool that merges features from
    SQANTI and SQANTI2, together with new additions. SQANTI3 will continue as an
    integrated development aiming to provide the best characterization for your
    new long read-defined transcriptome.
  doc_url: https://github.com/ConesaLab/SQANTI3/wiki
  dev_url: https://github.com/ConesaLab/SQANTI3

extra:
  recipe-maintainers:
    - ConesaLab
