"""Integration tests for SQANTI-reads (sqanti3_reads.py), fast mode.

Runs the tool end-to-end on the vendored chr22 fixture in
``test/test_data/sqanti_reads`` and checks that the expected tables/plots are
produced and that the CSV tables match the committed regression baseline.

The baseline in ``test/test_data/sqanti_reads/baseline`` was generated by the
current code with ``-ge 10`` (the fixture's genes top out at ~53 reads, so the
default ``-ge 100`` yields no qualifying genes). It is the regression oracle for
the Phase 1/2 refactor: outputs must stay numerically identical.

These tests need the external tools used by the UJC-hashing step
(``gffread``, ``gtftools``, ``bedtools``); the module is skipped if any are
missing so the suite stays portable.
"""
import os
import shutil
import subprocess
import sys

import pandas as pd
import pandas.testing as pdt
import pytest

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
DATA_DIR = os.path.join(REPO_ROOT, "test", "test_data", "sqanti_reads")
SQANTI_DIRS = os.path.join(DATA_DIR, "sqanti_dirs")
REF_GTF = os.path.join(DATA_DIR, "reference", "gencode.v38.basic_chr22.gtf")
BASELINE_DIR = os.path.join(DATA_DIR, "baseline")

# Read-count cutoff that lets the full pipeline run on this small fixture.
GENE_EXPRESSION = "10"

EXPECTED_CSVS = [
    "sqantiReads_cv.csv",
    "sqantiReads_gene_counts.csv",
    "sqantiReads_ujc_counts.csv",
    "sqantiReads_length_summary.csv",
    "sqantiReads_gene_classfication.csv",
    "sqantiReads_putative_underannotation.csv",
]
# Single unified report (QC plots + under-annotation section merged).
EXPECTED_PDFS = ["sqantiReads_report.pdf"]
# Page-count snapshots for the fixture at -ge 10, guarding against a merge that
# silently drops pages. Update these if plots are intentionally added/removed.
EXPECTED_REPORT_PAGES = {"design.csv": 42, "design_with_factor.csv": 44}

REQUIRED_TOOLS = ["gffread", "gtftools", "bedtools"]
_missing = [t for t in REQUIRED_TOOLS if shutil.which(t) is None]
pytestmark = pytest.mark.skipif(
    bool(_missing),
    reason="missing external tools required by SQANTI-reads: " + ", ".join(_missing),
)


def _run_reads(out_dir, design, factor=None):
    cmd = [
        sys.executable,
        os.path.join(REPO_ROOT, "sqanti3_reads.py"),
        "--design", os.path.join(DATA_DIR, design),
        "--sqanti_dirs", SQANTI_DIRS,
        "--refGTF", REF_GTF,
        "--refFasta", REF_GTF,  # fast mode does not read it; satisfies argparse today
        "--output", out_dir,
        "--prefix", "sqantiReads",
        "-ge", GENE_EXPRESSION,
        "--report", "pdf",
    ]
    if factor:
        cmd += ["--factor", factor]
    return subprocess.run(cmd, cwd=REPO_ROOT, capture_output=True, text=True)


def _assert_outputs_present(out_dir):
    for name in EXPECTED_CSVS + EXPECTED_PDFS:
        path = os.path.join(out_dir, name)
        assert os.path.isfile(path), f"missing output: {name}"
        assert os.path.getsize(path) > 0, f"empty output: {name}"


def _assert_single_merged_report(out_dir, design):
    """The report is one PDF containing both QC and under-annotation sections."""
    assert not os.path.exists(os.path.join(out_dir, "sqantiReads_annotation_plots.pdf")), \
        "the separate annotation PDF should no longer be produced"
    report = os.path.join(out_dir, "sqantiReads_report.pdf")
    pypdf = pytest.importorskip("pypdf")
    reader = pypdf.PdfReader(report)
    n_pages = len(reader.pages)
    assert n_pages == EXPECTED_REPORT_PAGES[design], \
        f"{design}: expected {EXPECTED_REPORT_PAGES[design]} pages, got {n_pages}"
    all_text = "\n".join((p.extract_text() or "") for p in reader.pages)
    assert "Under-annotation analysis" in all_text, \
        "merged report is missing the under-annotation section"
    return all_text


def _assert_titles_corrected(all_text):
    """Lock in the Phase-1b plot-title fixes (mislabels / typos)."""
    must_be_present = [
        "Percentage of Detected Donors",             # was "Number of Donors > 3 reads"
        "Percentage of FSM Reads in Each subcategory",  # was a duplicate count title
        "Number of Detected Acceptors",              # ylabel typo "Detetced" fixed
    ]
    must_be_absent = [
        "Number of Donors > 3 reads",
        "Detetced",
    ]
    for s in must_be_present:
        assert s in all_text, f"expected corrected title missing: {s!r}"
    for s in must_be_absent:
        assert s not in all_text, f"stale mislabeled title still present: {s!r}"


def _assert_matches_baseline(out_dir):
    for name in EXPECTED_CSVS:
        produced = pd.read_csv(os.path.join(out_dir, name))
        expected = pd.read_csv(os.path.join(BASELINE_DIR, name))
        pdt.assert_frame_equal(
            produced.reset_index(drop=True),
            expected.reset_index(drop=True),
            check_dtype=False,
            check_exact=False,
            rtol=1e-6,
            obj=name,
        )


def test_fast_mode_no_factor(tmp_path):
    out_dir = str(tmp_path / "out")
    result = _run_reads(out_dir, "design.csv")
    assert result.returncode == 0, f"non-zero exit\nSTDERR:\n{result.stderr}"
    _assert_outputs_present(out_dir)
    all_text = _assert_single_merged_report(out_dir, "design.csv")
    _assert_titles_corrected(all_text)
    _assert_matches_baseline(out_dir)


def test_fast_mode_with_factor(tmp_path):
    """The faceted (--factor) path must complete and produce both PDFs.

    Regression guard for the Phase-1 fix to plot_stacked_bars /
    plot_side_by_side_bars, which previously raised KeyError('100+ reads')
    when a read-count category was absent in a facet.
    """
    out_dir = str(tmp_path / "out")
    result = _run_reads(out_dir, "design_with_factor.csv", factor="group")
    assert result.returncode == 0, f"non-zero exit\nSTDERR:\n{result.stderr}"
    _assert_outputs_present(out_dir)
    _assert_single_merged_report(out_dir, "design_with_factor.csv")
    # Table CSVs are the same values as the no-factor run plus the factor column;
    # assert they at least match the baseline on shared columns.
    for name in EXPECTED_CSVS:
        produced = pd.read_csv(os.path.join(out_dir, name))
        expected = pd.read_csv(os.path.join(BASELINE_DIR, name))
        shared = [c for c in expected.columns if c in produced.columns]
        pdt.assert_frame_equal(
            produced[shared].reset_index(drop=True),
            expected[shared].reset_index(drop=True),
            check_dtype=False,
            check_exact=False,
            rtol=1e-6,
            obj=name,
        )
