"""Integration tests for SQANTI-reads (sqanti3_reads.py), fast mode.

Runs the tool end-to-end on the vendored chr22 fixture in
``test/test_data/sqanti_reads`` and checks that the expected tables/plots are
produced and that the CSV tables match the committed regression baseline.

The baseline in ``test/test_data/sqanti_reads/baseline`` was generated by the
current code with ``-ge 10`` (the fixture's genes top out at ~53 reads, so the
default ``-ge 100`` yields no qualifying genes). It is the regression oracle for
the Phase 1/2 refactor: outputs must stay numerically identical.

These tests need the external tools used by the UJC-hashing step
(``gffread``, ``gtftools``, ``bedtools``); the module is skipped if any are
missing so the suite stays portable.
"""
import os

import pandas as pd
import pandas.testing as pdt
import pytest

from .conftest import (
    BASELINE_DIR,
    DATA_DIR,
    requires_external_tools,
    run_reads,
)

EXPECTED_CSVS = [
    "sqantiReads_cv.csv",
    "sqantiReads_gene_counts.csv",
    "sqantiReads_ujc_counts.csv",
    "sqantiReads_length_summary.csv",
    "sqantiReads_gene_classfication.csv",
    "sqantiReads_putative_underannotation.csv",
]
# Single unified report (QC plots + under-annotation section merged).
EXPECTED_PDFS = ["sqantiReads_report.pdf"]
# Page-count snapshots for the fixture at -ge 10, guarding against a merge that
# silently drops pages. Update these if plots are intentionally added/removed.
# Both designs render through the single faceted path (render_report_pdf) and
# carry a summary-metrics page after the title page, so the counts match.
# The two designs now differ: the within-group replicate views (A5 multi-axis
# concordance, F7 splice-site precision concordance) render only with a --factor
# that has a >=2-replicate level, so they add 2 pages to the faceted design only.
EXPECTED_REPORT_PAGES = {"design.csv": 63, "design_with_factor.csv": 65}

pytestmark = requires_external_tools

# Back-compat alias: this module historically called the runner ``_run_reads``.
_run_reads = run_reads


def _assert_outputs_present(out_dir):
    for name in EXPECTED_CSVS + EXPECTED_PDFS:
        path = os.path.join(out_dir, name)
        assert os.path.isfile(path), f"missing output: {name}"
        assert os.path.getsize(path) > 0, f"empty output: {name}"


def _assert_single_merged_report(out_dir, design):
    """The report is one PDF containing both QC and under-annotation sections."""
    assert not os.path.exists(os.path.join(out_dir, "sqantiReads_annotation_plots.pdf")), \
        "the separate annotation PDF should no longer be produced"
    report = os.path.join(out_dir, "sqantiReads_report.pdf")
    pypdf = pytest.importorskip("pypdf")
    reader = pypdf.PdfReader(report)
    n_pages = len(reader.pages)
    assert n_pages == EXPECTED_REPORT_PAGES[design], \
        f"{design}: expected {EXPECTED_REPORT_PAGES[design]} pages, got {n_pages}"
    all_text = "\n".join((p.extract_text() or "") for p in reader.pages)
    assert "Under-annotation analysis" in all_text, \
        "merged report is missing the under-annotation section"
    return all_text


def _assert_titles_corrected(all_text):
    """Lock in the canonical plot titles (single faceted render path)."""
    must_be_present = [
        "Percentage of Detected Donors",                  # was "Number of Donors > 3 reads"
        "Percentage of FSM Reads in Each Sub-Category",   # faceted sub-category title
        "Number of Detected Acceptors",                   # ylabel typo "Detetced" fixed
    ]
    must_be_absent = [
        "Number of Donors > 3 reads",
        "Detetced",
    ]
    for s in must_be_present:
        assert s in all_text, f"expected corrected title missing: {s!r}"
    for s in must_be_absent:
        assert s not in all_text, f"stale mislabeled title still present: {s!r}"


def _assert_matches_baseline(out_dir):
    for name in EXPECTED_CSVS:
        produced = pd.read_csv(os.path.join(out_dir, name))
        expected = pd.read_csv(os.path.join(BASELINE_DIR, name))
        pdt.assert_frame_equal(
            produced.reset_index(drop=True),
            expected.reset_index(drop=True),
            check_dtype=False,
            check_exact=False,
            rtol=1e-6,
            obj=name,
        )


def test_fast_mode_no_factor(tmp_path):
    out_dir = str(tmp_path / "out")
    result = _run_reads(out_dir, "design.csv")
    assert result.returncode == 0, f"non-zero exit\nSTDERR:\n{result.stderr}"
    _assert_outputs_present(out_dir)
    all_text = _assert_single_merged_report(out_dir, "design.csv")
    _assert_titles_corrected(all_text)
    _assert_matches_baseline(out_dir)


def test_fast_mode_with_factor(tmp_path):
    """The faceted (--factor) path must complete and produce both PDFs.

    Regression guard for the Phase-1 fix to plot_stacked_bars /
    plot_side_by_side_bars, which previously raised KeyError('100+ reads')
    when a read-count category was absent in a facet.
    """
    out_dir = str(tmp_path / "out")
    result = _run_reads(out_dir, "design_with_factor.csv", factor="group")
    assert result.returncode == 0, f"non-zero exit\nSTDERR:\n{result.stderr}"
    _assert_outputs_present(out_dir)
    _assert_single_merged_report(out_dir, "design_with_factor.csv")
    # Table CSVs are the same values as the no-factor run plus the factor column;
    # assert they at least match the baseline on shared columns.
    for name in EXPECTED_CSVS:
        produced = pd.read_csv(os.path.join(out_dir, name))
        expected = pd.read_csv(os.path.join(BASELINE_DIR, name))
        shared = [c for c in expected.columns if c in produced.columns]
        pdt.assert_frame_equal(
            produced[shared].reset_index(drop=True),
            expected[shared].reset_index(drop=True),
            check_dtype=False,
            check_exact=False,
            rtol=1e-6,
            obj=name,
        )


def test_fast_mode_uppercase_factor(tmp_path):
    """A --factor whose name starts with an uppercase letter must not crash.

    Regression guard: prep_data_4_plots renamed every PCA length column whose
    name started with an uppercase letter, which also caught the factor column
    (e.g. ``RIN_group`` -> ``perc_reads_RIN_group``) and then raised
    ``KeyError: ['RIN_group'] not found in axis`` at the following ``drop()``.
    The fixture's own factor (``group``) is lowercase, so this is exercised with
    a dedicated uppercase-named factor.
    """
    out_dir = str(tmp_path / "out")
    result = _run_reads(out_dir, "design_with_upper_factor.csv", factor="RIN_group")
    assert result.returncode == 0, f"non-zero exit\nSTDERR:\n{result.stderr}"
    _assert_outputs_present(out_dir)
    # Same page count as the lowercase-factor faceted run (only the factor name differs).
    _assert_single_merged_report(out_dir, "design_with_factor.csv")


def test_fast_mode_single_sample(tmp_path):
    """A single-sample cohort must not crash the PDF report.

    Regression guard: with one sample PCA collapses to a single component, so
    ``pca_DF`` has no column 1 and the PDF's ``_scatter_labeled(pca_DF, 0, 1, ...)``
    raised ``KeyError: 1``. The cohort-relative views (PCA, concordance, overlap,
    scorecard) skip for n=1; the per-sample views (composition, length, CAGE/polyA
    support when present) still render. Only the run completing is asserted.
    """
    out_dir = str(tmp_path / "out")
    result = _run_reads(out_dir, "design_single.csv", report="both")
    assert result.returncode == 0, f"non-zero exit\nSTDERR:\n{result.stderr}"
    assert os.path.getsize(os.path.join(out_dir, "sqantiReads_report.pdf")) > 0
    assert os.path.getsize(os.path.join(out_dir, "sqantiReads_report.html")) > 0


# Section headings expected in the interactive HTML report.
HTML_SECTIONS = [
    "Summary &amp; QC flags",
    "Reads per structural category — all genes",
    "Per-gene structural-category distribution",
    "Genes detected, by read support",
    "Unique junction chains, by structural category",
    "UJCs, by read support",
    "Read length distribution",
    "Read length distribution (raw)",
    "Sequencing depth vs read length",
    "FSM reads by sub-category",
    "Junction classification (%)",
    "Potential artefacts",
    "Splice-donor detection variation",
    "Splice-acceptor detection variation",
    "Sample similarity (PCA)",
    "PCA loadings",
    "UJC saturation",
    "UJC saturation by structural category",
    "Replicate concordance",
    "Shared UJCs across samples (UpSet)",
    "Pairwise UJC overlap index",
    "Under-annotation analysis",
    "Optional orthogonal support",
]


def test_html_report(tmp_path):
    """--report html produces a single self-contained interactive report + JSON."""
    import json

    out_dir = str(tmp_path / "out")
    result = _run_reads(out_dir, "design.csv", report="html")
    assert result.returncode == 0, f"non-zero exit\nSTDERR:\n{result.stderr}"

    html = os.path.join(out_dir, "sqantiReads_report.html")
    js_summary = os.path.join(out_dir, "sqantiReads_qc_summary.json")
    assert os.path.getsize(html) > 0, "HTML report missing/empty"
    assert os.path.getsize(js_summary) > 0, "qc_summary.json missing/empty"
    # html-only: no PDF
    assert not os.path.exists(os.path.join(out_dir, "sqantiReads_report.pdf"))

    text = open(html, encoding="utf-8").read()
    # Self-contained: plotly inlined, no external resource loads
    assert "Plotly.newPlot" in text, "plotly figures not embedded"
    import re
    external = re.findall(r'<(?:script[^>]*src|link[^>]*href|img[^>]*src)="https?://', text)
    assert not external, f"report loads external resources (not offline-safe): {external}"
    for section in HTML_SECTIONS:
        assert section in text, f"HTML report missing section: {section}"

    summary = json.load(open(js_summary))
    assert summary["n_samples"] == 3
    assert set(summary["samples"]) == {"SQ_R1", "SQ_R2", "SQ_R3"}
    for s, m in summary["samples"].items():
        assert "flags" in m and "overall_flag" in m, f"{s} missing flags"
        assert m["overall_flag"] in {"pass", "warn", "fail"}
        assert m["total_reads"] > 0


def test_html_report_faceted(tmp_path):
    """--factor + --report html produces a faceted interactive report."""
    import json

    out_dir = str(tmp_path / "out")
    result = _run_reads(out_dir, "design_with_factor.csv", factor="group", report="html")
    assert result.returncode == 0, f"non-zero exit\nSTDERR:\n{result.stderr}"

    html = os.path.join(out_dir, "sqantiReads_report.html")
    text = open(html, encoding="utf-8").read()
    # Faceting splits each figure into one subplot per factor level.
    assert "groupA" in text and "groupB" in text, "facet level labels not in report"
    assert "Plotly.newPlot" in text

    summary = json.load(open(os.path.join(out_dir, "sqantiReads_qc_summary.json")))
    assert summary["factor"] == "group"


def test_parallel_jobs_match_serial(tmp_path):
    """--jobs>1 (parallel per-sample processing) must give identical tables."""
    out_dir = str(tmp_path / "out")
    result = _run_reads(out_dir, "design.csv", jobs=3)
    assert result.returncode == 0, f"non-zero exit\nSTDERR:\n{result.stderr}"
    _assert_outputs_present(out_dir)
    _assert_matches_baseline(out_dir)  # same as the serial baseline


def test_config_overrides_qc_thresholds(tmp_path):
    """A --config YAML overrides the QC-flag thresholds in the report + JSON."""
    import json

    cfg = tmp_path / "cfg.yaml"
    cfg.write_text(
        "qc_flags:\n"
        "  perc_reads_intrapriming:\n"
        "    warn: 5.0\n"
        "    fail: 10.0\n"
        "    worse: high\n"
        "    label: \"Intra-priming reads (%)\"\n"
    )
    out_dir = str(tmp_path / "out")
    result = _run_reads(out_dir, "design.csv", report="html", config=str(cfg))
    assert result.returncode == 0, f"non-zero exit\nSTDERR:\n{result.stderr}"

    summary = json.load(open(os.path.join(out_dir, "sqantiReads_qc_summary.json")))
    spec = summary["thresholds"]["perc_reads_intrapriming"]
    assert spec["warn"] == 5.0 and spec["fail"] == 10.0, "config threshold not applied"
    # Fixture intra-priming is ~19-20%, so every sample now fails that metric.
    for s, m in summary["samples"].items():
        assert m["flags"]["perc_reads_intrapriming"] == "fail", f"{s} not flagged"
