"""Integration tests for SQANTI-reads (sqanti3_reads.py), fast mode.

Runs the tool end-to-end on the vendored chr22 fixture in
``test/test_data/sqanti_reads`` and checks that the expected tables/plots are
produced and that the CSV tables match the committed regression baseline.

The baseline in ``test/test_data/sqanti_reads/baseline`` was generated by the
current code with ``-ge 10`` (the fixture's genes top out at ~53 reads, so the
default ``-ge 100`` yields no qualifying genes). It is the regression oracle for
the Phase 1/2 refactor: outputs must stay numerically identical.

These tests need the external tools used by the UJC-hashing step
(``gffread``, ``gtftools``, ``bedtools``); the module is skipped if any are
missing so the suite stays portable.
"""
import os
import shutil
import subprocess
import sys

import pandas as pd
import pandas.testing as pdt
import pytest

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
DATA_DIR = os.path.join(REPO_ROOT, "test", "test_data", "sqanti_reads")
SQANTI_DIRS = os.path.join(DATA_DIR, "sqanti_dirs")
REF_GTF = os.path.join(DATA_DIR, "reference", "gencode.v38.basic_chr22.gtf")
BASELINE_DIR = os.path.join(DATA_DIR, "baseline")

# Read-count cutoff that lets the full pipeline run on this small fixture.
GENE_EXPRESSION = "10"

EXPECTED_CSVS = [
    "sqantiReads_cv.csv",
    "sqantiReads_gene_counts.csv",
    "sqantiReads_ujc_counts.csv",
    "sqantiReads_length_summary.csv",
    "sqantiReads_gene_classfication.csv",
    "sqantiReads_putative_underannotation.csv",
]
EXPECTED_PDFS = ["sqantiReads_plots.pdf", "sqantiReads_annotation_plots.pdf"]

REQUIRED_TOOLS = ["gffread", "gtftools", "bedtools"]
_missing = [t for t in REQUIRED_TOOLS if shutil.which(t) is None]
pytestmark = pytest.mark.skipif(
    bool(_missing),
    reason="missing external tools required by SQANTI-reads: " + ", ".join(_missing),
)


def _run_reads(out_dir, design, factor=None):
    cmd = [
        sys.executable,
        os.path.join(REPO_ROOT, "sqanti3_reads.py"),
        "--design", os.path.join(DATA_DIR, design),
        "--sqanti_dirs", SQANTI_DIRS,
        "--refGTF", REF_GTF,
        "--refFasta", REF_GTF,  # fast mode does not read it; satisfies argparse today
        "--output", out_dir,
        "--prefix", "sqantiReads",
        "-ge", GENE_EXPRESSION,
        "--report", "pdf",
    ]
    if factor:
        cmd += ["--factor", factor]
    return subprocess.run(cmd, cwd=REPO_ROOT, capture_output=True, text=True)


def _assert_outputs_present(out_dir):
    for name in EXPECTED_CSVS + EXPECTED_PDFS:
        path = os.path.join(out_dir, name)
        assert os.path.isfile(path), f"missing output: {name}"
        assert os.path.getsize(path) > 0, f"empty output: {name}"


def _assert_matches_baseline(out_dir):
    for name in EXPECTED_CSVS:
        produced = pd.read_csv(os.path.join(out_dir, name))
        expected = pd.read_csv(os.path.join(BASELINE_DIR, name))
        pdt.assert_frame_equal(
            produced.reset_index(drop=True),
            expected.reset_index(drop=True),
            check_dtype=False,
            check_exact=False,
            rtol=1e-6,
            obj=name,
        )


def test_fast_mode_no_factor(tmp_path):
    out_dir = str(tmp_path / "out")
    result = _run_reads(out_dir, "design.csv")
    assert result.returncode == 0, f"non-zero exit\nSTDERR:\n{result.stderr}"
    _assert_outputs_present(out_dir)
    _assert_matches_baseline(out_dir)


def test_fast_mode_with_factor(tmp_path):
    """The faceted (--factor) path must complete and produce both PDFs.

    Regression guard for the Phase-1 fix to plot_stacked_bars /
    plot_side_by_side_bars, which previously raised KeyError('100+ reads')
    when a read-count category was absent in a facet.
    """
    out_dir = str(tmp_path / "out")
    result = _run_reads(out_dir, "design_with_factor.csv", factor="group")
    assert result.returncode == 0, f"non-zero exit\nSTDERR:\n{result.stderr}"
    _assert_outputs_present(out_dir)
    # Table CSVs are the same values as the no-factor run plus the factor column;
    # assert they at least match the baseline on shared columns.
    for name in EXPECTED_CSVS:
        produced = pd.read_csv(os.path.join(out_dir, name))
        expected = pd.read_csv(os.path.join(BASELINE_DIR, name))
        shared = [c for c in expected.columns if c in produced.columns]
        pdt.assert_frame_equal(
            produced[shared].reset_index(drop=True),
            expected[shared].reset_index(drop=True),
            check_dtype=False,
            check_exact=False,
            rtol=1e-6,
            obj=name,
        )
